builds:
  - main: main.go
    binary: "terraform-provider-cloudstack_{{.Tag}}_x-exoscale-{{.Commit}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

sign:
  cmd: gpg
  args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: all


dist: build

git:
  short_hash: true
